// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectRestanta.Data;

#nullable disable

namespace ProiectRestanta.Migrations
{
    [DbContext(typeof(ProiectContext))]
    [Migration("20220829204251_AddedManyToMany")]
    partial class AddedManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProiectRestanta.Entities.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salariu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bosses");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Design", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Culoare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pret")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Designs");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Shirt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Culoare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Shirts");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.ShirtDesign", b =>
                {
                    b.Property<int>("ShirtId")
                        .HasColumnType("int");

                    b.Property<int>("DesignId")
                        .HasColumnType("int");

                    b.HasKey("ShirtId", "DesignId");

                    b.HasIndex("DesignId");

                    b.ToTable("ShirtDesigns");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BossId")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BossId")
                        .IsUnique();

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Shirt", b =>
                {
                    b.HasOne("ProiectRestanta.Entities.Shop", "Shop")
                        .WithMany("Shirts")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.ShirtDesign", b =>
                {
                    b.HasOne("ProiectRestanta.Entities.Shirt", "Shirt")
                        .WithMany("ShirtDesigns")
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectRestanta.Entities.Design", "Design")
                        .WithMany("ShirtDesigns")
                        .HasForeignKey("ShirtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Design");

                    b.Navigation("Shirt");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Shop", b =>
                {
                    b.HasOne("ProiectRestanta.Entities.Boss", "Boss")
                        .WithOne("Shop")
                        .HasForeignKey("ProiectRestanta.Entities.Shop", "BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boss");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Boss", b =>
                {
                    b.Navigation("Shop")
                        .IsRequired();
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Design", b =>
                {
                    b.Navigation("ShirtDesigns");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Shirt", b =>
                {
                    b.Navigation("ShirtDesigns");
                });

            modelBuilder.Entity("ProiectRestanta.Entities.Shop", b =>
                {
                    b.Navigation("Shirts");
                });
#pragma warning restore 612, 618
        }
    }
}
